kind: pipeline
name: default

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: install
    image: node:8.16-alpine
    commands:
      - yarn

  - name: test
    image: node:8.16-alpine
    commands:
      - yarn test-ci

  - name: release
    image: node:8.16
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
      - npm run release
    when:
      event: push
      branch: master
